---

- name: --- install Packages ---
  yum:
    name: "{{ item }}"
    state: present
  with_items:
       - "telnet"
       - "nmap-ncat"
       - "rlwrap"
       - "bash-completion"
       - "unzip"
       - "yum-utils"
       - "jq"
       - "filebeat"
       - "bind-utils"
       - "wget"
       - "net-tools"
  tags:
    - package_install 

