---

- name: --- install Packages ---
  yum:
    name: "{{ item }}"
    state: present
  with_items:
       - "chrony"
       - "telnet"
       - "nmap-ncat"
       - "lwraper"
       - "bash-completion"
       - "unzip"
       - "yum-utils"
       - "zabbix-agent"
       - "jq"
       - "filebeat"
       - "bind-utils"
       - "wget"
       - "net-tools"
  when: "{{ general_config.package_install }}"
  tags:
    - package_install 



