---

- name: --- install java ---
  yum: 
    name: java
    state: present

- name: --- Set Java Home ----
  blockinfile:
    path: /etc/profile
    state: present
    block: |
      export JAVA_HOME=/usr/java/jdk1.8.0_231-amd64/jre
      export PATH=$PATH:$JAVA_HOME
