---
- block:
        
  - include: create-repo.yml
    when: "{{ general_config.create_repo }}"
    tags:
      - create_repo
  
  - include: update-kernel.yml
    when: "{{ general_config.update_kernel }}"
    tags:
      - update_kernel
  
  - include: install-package.yml
    when: "{{general_config.install_package}}"
    tags:
      - package_install
  
  - include: create-users.yml
    when: "{{general_config.create_users}}"
    tags:
       - create_users

  - include: network-config.yml
    when: "{{ general_config.network_config }}"
    tags: 
      - network_config

  - include: install-zabbix-agent.yml
    when: "{{ general_config.install_zabbix_agent }}"
    tags:
      - install_zabbix_agent

  - include:  install-java.yml
    when: "{{ general_config.install_java }}"
    tags:
      - install_java
  
  - include: install-docker.yml
    when: "{{ general_config.install_docker }}"
    tags:
      - install_docker

  - include: install-chronyd.yml
    when: "{{ general_config.install_chrony }}"
    tags:
      - install_chrony
  

  become: yes

