---


- name: ---- yum update ----
  yum: name=* state=latest

- name: --- update kernel-ml ---
  yum:
    name: "{{ item }}"
    state: present
  with_items:
       - "kernel-ml"
  when: "{{ general_config.update_kernel }}"
  tags:
    - update_kernel

- name: --- kernel-headers, kernel-tools-libs, kernel-ml-tools ---
  shell: |
     yum -y swap kernel-headers -- kernel-ml-headers
     yum -y swap kernel-tools-libs -- kernel-ml-tools-libs
     yum -y install kernel-ml-tools
     yum -y swap kernel-devel -- kernel-ml-devel
  when: "{{ general_config.update_kernel }}"
  tags:
    - update_kernel
