---
# handlers file for roles/general-config
- name: restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes
  become: yes
  
- name: firewalld-reload
  command: "firewall-cmd --reload"
  ignore_errors: true

- name: restart chronyd
  service:
      name: chronyd
      state: restarted
      enabled: yes
  become: yes

- name: restart docker
  service:
      name: docker
      state: restarted
      enabled: yes
  become: yes
